language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

env: 
  matrix: 
  - Config=.smalltalk.ston
  - Config=.smalltalk.CommentRender.ston

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo64-8.0

script: 
  - smalltalkci ${Config}